[general.plugin_registry.plugins]
  harpverify = "/lus/h2resw01/hpcperm/snh02/DE_Verification/plugins/"
[platform]
  deode_home = "set-by-the-system"
[suite_control]
  suite_definition = "HarpverifySuiteDefinition"
[impact.verification]
  verification_prefix="DE_Verification_HARP_" # When used in on-duty team runs, align this with platform.impact.verification.suite_prefix
[scheduler.ecfvars]
  case_prefix = "DE_Verification_HARP_" # Add this to the suite name to not collide with OD case runs.
  #ecf_host = "ecflow-gen-snh02-001" # Hardcode your ecflow server (needed after v0.12.0)
  ecf_host = "ecflow-gen-sp3c-001"
[submission]
  submit_types = ["background_vm", "background_hpc", "parallel", "gnu", "serial", "harpverify_group"]

[submission.harpverify_group]
  SCHOST = "hpc"                             # Refers to the submission group in troika
  tasks = ["LinkOBSFCTABLES", "Verification", "Filesave"]
  WRAPPER = ""
  delay = "PT1D"  #How long to delay the start of the suite, refered to the nominal end of the run.
                     #A safe value here is 24h after the end of the run, when all obs should be available and processed

[submission.harpverify_group.BATCH]
  NAME = "#SBATCH --job-name=@TASK_NAME@"
  NODES = "#SBATCH --nodes=1"
  NTASKS = "#SBATCH --ntasks=1"
  WALLTIME = "#SBATCH --time=01:05:00"

[submission.harpverify_group.ENV]
  DEODE = "awesome"
  DUSER = "sp3c"   # DEODE User: who ran the DEODE case
  HUSER = "sp3c"   # HARP User : who runs the HARP verification 
  HARPSCRIPTS_HOME = "/lus/h2resw01/hpcperm/snh02/DE_Verification/verif_tools/oper-harp-verif/" # Path to your HARP SCRIPTS installation
  VERIF_HOME= "/ec/res4/hpcperm/sp3c/DE_Verification/deode_harp_output/" # Root path for HARP results, config files, OBSTABLES and FCTABLES..
  REF_SQLITES="/ec/res4/scratch/snh02/DE_Verification/REF_FCTABLES/" # Where to find sqlites for the reference models
  OBSTABLES_PATH="/ec/res4/hpcperm/snh02/DE_Verification/yyyymm_vobstables/"
  REF_NAME=["GDT_iekm","IFS"] # Names of your reference models
  #REF_NAME=["AROME_750m","HARMONIE_AROME_750m","IFSENS"]
  ECFS_ARCHIVE_RELPATH_HARPOUTPUT="/deode/HARP_VERIF/cases/" # Root to store the HARP results in permanent archive
  ECFS_ARCHIVE_RELPATH_DEODEOUTPUT="/deode/" #Normally /deode/ for generic users, /DE_NWP/deode/ for operational (aut6432)
  DCMDB_DIR="/ec/res4/hpcperm/snh02/DE_Verification/verif_tools/dcmdb/" #DCMDB installation. Only used if running the batch script for On-duty runs at once
  DW_DIR="/perm/snh02/DE_Verification/Deode-Workflow/" # Deode-Workflow installation
  RDSS_PATH="/ec/res4/hpcperm/sp3c/DE_Verification/deode_harp_output/RDSs" # Path to store your HARP results (in subfolders for each case)
  PNGS_PATH="/ec/res4/hpcperm/sp3c/DE_Verification/deode_harp_output/PNGs" # Path to store your HARP figures (in subfolders for each case)
  USE_OPERATIONAL_INDEXING="yes" # Whether to use the Operational indexing (use in combination with operational DUSER=aut6432)
  OBS_STEP=3 # Frequecy of observations. Use 1 or 3 hours, tipically
  Renv_conf="/perm/snh02/DE_Verification/Renv_oper/Setenv"  # File to source before running R scripts to get Renv with the HARP installation

[submission.harpverify_group.MODULES]
  ECFLOW = ["load", "ecflow"]
  #PYTHON311 = ["load", "python3/3.11.8-01"]
  #R433 = ["load", "R/4.4.3"]

[submission.task_exceptions.LinkOBSFCTABLES.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.Verification.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.Filesave.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"


#[boundaries]
#  bdmodel = "ifs"  # Might be needed when verifying cases run using DW before v0.13.0

#[boundaries.ifs]
#  bdmember = ["a"]    # Might be needed when verifying cases run using DW before v0.13.0

